execute pathogen#infect()
execute pathogen#helptags()

syntax enable
set number
set background=dark
let g:solarized_termtrans=1
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme solarized

let mapleader=" "
let g:notes_directories = ['~/Documents/Notes']

"map <C-o> :NERDTreeToggle<CR>
"autocmd StdinReadPre * let s:std_in=1
"autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
"autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

let g:airline_powerline_fonts = 1
set laststatus=2
if $COLORTERM == 'gnome-terminal'
    set t_Co=256
endif

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

nnoremap <Leader>m :w <BAR> !lessc % > %:t:r.css<CR><space>
set tabstop=4
set shiftwidth=4
set expandtab

filetype plugin on

