execute pathogen#infect()
execute pathogen#helptags()

syntax enable
set number
set background=dark
let g:solarized_termtrans=1
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme solarized

let g:notes_directories = ['~/Documents/Notes']

nnoremap <Leader>m :w <BAR> !lessc % > %:t:r.css<CR><space>
set tabstop=4
set shiftwidth=4
set expandtab
