call pathogen#infect()
call pathogen#helptags()

syntax enable
set number
set background=light
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme solarized

nnoremap <Leader>m :w <BAR> !lessc % > %:t:r.css<CR><space>

